# Generated by Django 4.2.7 on 2023-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcahub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='dob',
            field=models.CharField(max_length=20),
        ),
    ]
