# Generated by Django 4.2.7 on 2023-12-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcahub', '0002_alter_traveller_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeysearch',
            name='dob',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='riskaction',
            name='dob',
            field=models.CharField(max_length=20),
        ),
    ]
